### ISSUE TITLE
Grafana Unsealed events

### ISSUE THREAD

**Issue by jicarriches** [bitnami-labs/sealed-secrets#536]
Hello,

I have a lot of Openshift Unsealed events in Grafana. The event have the following info:

event.reason: Unsealed
verb: UPDATE
kubernetes.container.name: kube-eventrouter
event.message: Sealed Secret unsealed sucesfully
event.source.component: sealed-secrets

Which is the meaning of these events? Why I have a lot of these events on a single namespace?

Thank you.

**Comment by goober** [comment]
It should have been fixed by https://github.com/bitnami-labs/sealed-secrets/pull/525

**Comment by jicarriches** [comment]
Thank you @goober

**Comment by jicarriches** [comment]
Hello @goober,

I have installed the secret-sealed release 0.15.0 and the event still appearing.

Thank you,

**Comment by mkmik** [comment]
the community rocks!

**Comment by jicarriches** [comment]
Hey! Why do you close this issue?

**Comment by mkmik** [comment]
my mistake

**Comment by mkmik** [comment]
(when I read this ticket I missed the comment https://github.com/bitnami-labs/sealed-secrets/issues/536#issuecomment-788747352; perhaps a GH rendering issue)

**Comment by mkmik** [comment]
@jicarriches could you give more information about your setup?

which version of k8s? are you installing sealed-secrets with the yaml manifests or with the helm chart (if yes, exactly which chart version and which installation parameters).

Another question: do you see a non-0 restart count in the sealed-secret controller pod?

**Comment by jicarriches** [comment]
Is the k8s version of OCP 3.11, the 1.11. 
We don't use helm, it may be the yaml manifest of sealed-secrets
The sealed-secrets pod have been restarted since 160 days.

**Comment by jicarriches** [comment]
Hi @goober and @mkmik,

The 0.15.0 solve this issue.

Thank you very much for your support.

**Comment by mkmik** [comment]
can we close this now?

**Comment by jicarriches** [comment]
We must investigate further. Close by now. Thank you.

**Comment by mkmik** [comment]
sure, feel free to reopen it any time when you see a problem! thanks!
